// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package pgmodel

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Entitlement struct {
	ID             int64
	GuildID        int64
	SubscriptionID pgtype.Int8
	Type           string
	PlanIds        []string
	StartsAt       pgtype.Timestamp
	EndsAt         pgtype.Timestamp
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
}

type Guild struct {
	ID          int64
	Name        string
	Description pgtype.Text
	Icon        pgtype.Text
	Unavailable bool
	Deleted     bool
	OwnerUserID int64
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type GuildManager struct {
	GuildID   int64
	UserID    int64
	Role      string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type GuildSetting struct {
	GuildID       int64
	CommandPrefix pgtype.Text
	ColorScheme   pgtype.Text
	UpdatedAt     pgtype.Timestamp
}

type ModuleSetting struct {
	GuildID           int64
	ModuleID          string
	Enabled           bool
	CommandOverwrites []byte
	Config            []byte
	UpdatedAt         pgtype.Timestamp
}

type ModuleValue struct {
	ID        int64
	GuildID   int64
	ModuleID  string
	Key       string
	Value     []byte
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Session struct {
	KeyHash        string
	UserID         int64
	TokenAccess    string
	TokenRefresh   string
	TokenScopes    []string
	TokenExpiresAt pgtype.Timestamp
	Guilds         []byte
	CreatedAt      pgtype.Timestamp
	ExpiresAt      pgtype.Timestamp
}

type Subscription struct {
	ID                    int64
	UserID                int64
	Status                string
	PaddleSubscriptionID  string
	PaddleCustomerID      string
	PaddleProductIds      []string
	PaddlePriceIds        []string
	CreatedAt             pgtype.Timestamp
	StartedAt             pgtype.Timestamp
	PausedAt              pgtype.Timestamp
	CanceledAt            pgtype.Timestamp
	CurrentPeriodEndsAt   pgtype.Timestamp
	CurrentPeriodStartsAt pgtype.Timestamp
	UpdatedAt             pgtype.Timestamp
}

type User struct {
	ID            int64
	Username      string
	Discriminator pgtype.Text
	DisplayName   string
	Avatar        pgtype.Text
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
}
