// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user.sql

package pgmodel

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUser = `-- name: GetUser :one
SELECT id, username, discriminator, display_name, avatar, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Discriminator,
		&i.DisplayName,
		&i.Avatar,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (
    id,
    username,
    discriminator,
    display_name,
    avatar,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) ON CONFLICT (id) 
DO UPDATE SET 
    username = EXCLUDED.username,
    discriminator = EXCLUDED.discriminator,
    display_name = EXCLUDED.display_name,
    avatar = EXCLUDED.avatar,
    updated_at = EXCLUDED.updated_at
RETURNING id, username, discriminator, display_name, avatar, created_at, updated_at
`

type UpsertUserParams struct {
	ID            int64
	Username      string
	Discriminator pgtype.Text
	DisplayName   string
	Avatar        pgtype.Text
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser,
		arg.ID,
		arg.Username,
		arg.Discriminator,
		arg.DisplayName,
		arg.Avatar,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Discriminator,
		&i.DisplayName,
		&i.Avatar,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
