[defaults]
command_prefix = "o!"
color_scheme = "purple"

[api]
host = "localhost"
port = 8080
public_base_url = "http://localhost:8080"
strict_cookies = true

[app]
public_base_url = "http://localhost:3000"

[database.postgres]
host = "127.0.0.1"
port = 5432
user = "postgres"
db_name = "nook"

[database.s3]
endpoint = "localhost:9000"
access_key_id = "nook"
secret_access_key = "1234567890"

[billing]
paddle_environment = "sandbox"

[[billing.plans]]
id = "default"
title = "Default"
description = "The default plan for users that have no subscription."
default = true
hidden = true
feature_basic_access = true
