// Code generated by tygo. DO NOT EDIT.

//////////
// source: config.go

export interface BillingConfig {
}

//////////
// source: wire.go

export interface BillingPlanWire {
  id: string;
  title: string;
  description: string;
  default: boolean;
  popular: boolean;
  hidden: boolean;
  paddle_monthly_price_id?: string;
  paddle_yearly_price_id?: string;
  discord_role_id: string;
  features: BillingFeaturesWire;
}
export type BillingPlanListResponseWire = BillingPlanWire[];
export interface BillingFeaturesWire {
  plan_id: string;
  basic_access: boolean;
}
export type BillingFeaturesGetResponseWire = BillingFeaturesWire;
export interface SubscriptionWire {
  id: string;
  user_id: string;
  status: string;
  paddle_subscription_id: string;
  paddle_customer_id: string;
  paddle_product_ids: string[];
  paddle_price_ids: string[];
  created_at: string /* RFC3339 */;
  started_at: null | string /* RFC3339 */;
  paused_at: null | string /* RFC3339 */;
  canceled_at: null | string /* RFC3339 */;
  current_period_ends_at: null | string /* RFC3339 */;
  current_period_starts_at: null | string /* RFC3339 */;
  updated_at: string /* RFC3339 */;
  manageable: boolean;
}
export type SubscriptionListResponseWire = SubscriptionWire[];
export interface SubscriptionManageResponseWire {
  cancel_url: string;
  update_payment_method_url: string;
}
