// Code generated by tygo. DO NOT EDIT.
import { UserWire } from "./user.gen";

//////////
// source: config.go

export interface GuildConfig {
}

//////////
// source: wire.go

export interface GuildWire {
  id: string /* Snowflake */;
  name: string;
  icon: null | string;
  owner: boolean;
  permissions: string /* discord.Permissions */;
  bot: boolean;
  access: boolean;
}
export type GuildGetResponseWire = GuildWire;
export type GuildListResponseWire = GuildWire[];
export interface ChannelWire {
  id: string /* Snowflake */;
  type: number /* discord.ChannelType */;
  name: string;
  position: number /* int */;
}
export type ChannelGetResponseWire = ChannelWire;
export type ChannelListResponseWire = ChannelWire[];
export interface RoleWire {
  id: string /* Snowflake */;
  name: string;
  permissions: string /* discord.Permissions */;
  position: number /* int */;
  color: string;
}
export type RoleGetResponseWire = RoleWire;
export type RoleListResponseWire = RoleWire[];
export interface GuildSettingsWire {
  command_prefix: null | string;
  color_scheme: null | string;
  default: DefaultGuildSettingsWire;
}
export interface DefaultGuildSettingsWire {
  command_prefix: string;
  color_scheme: string;
  resolved_color: string;
}
export type GuildSettingsGetResponseWire = GuildSettingsWire;
export interface GuildSettingsUpdateRequestWire {
  command_prefix?: string;
  color_scheme?: string;
}
export type GuildSettingsUpdateResponseWire = GuildSettingsWire;
export interface GuildManagerWire {
  guild_id: string /* Snowflake */;
  user: UserWire;
  role: any /* model.GuildManagerRole */;
  created_at: string /* RFC3339 */;
  updated_at: string /* RFC3339 */;
}
export type GuildManagerListResponseWire = GuildManagerWire[];
export interface GuildManagerCreateAddWire {
  user_id: string /* Snowflake */;
  role: any /* model.GuildManagerRole */;
}
export type GuildManagerAddAddResponseWire = GuildManagerWire;
export interface GuildManagerRemoveResponseWire {
}
export interface GuildProfileWire {
  user_id: string /* Snowflake */;
  custom_name?: string;
  default_name: string;
  custom_bio?: string;
  default_bio?: string;
  custom_avatar_url?: string;
  default_avatar_url?: string;
}
export type GuildProfileGetResponseWire = GuildProfileWire;
export interface GuildProfileUpdateRequestWire {
  name: string;
  bio: string;
  avatar?: string;
}
export type GuildProfileUpdateResponseWire = GuildProfileWire;
