// Code generated by tygo. DO NOT EDIT.

//////////
// source: config.go

export interface UserConfig {
}

//////////
// source: wire.go

export interface UserWire {
  id: string /* Snowflake */;
  username: string;
  discriminator: string;
  display_name: string;
  avatar: null | string;
  created_at: string /* RFC3339 */;
  updated_at: string /* RFC3339 */;
}
export type UserGetResponseWire = UserWire;
